### ISSUE TITLE
Uploaded images not showing up under account 

### ISSUE THREAD

**Issue by MostHated** [faustocarrera/imgur-python#17]
Hey there,
    I had been using [imgur-Screenshot](https://github.com/jomo/imgur-screenshot) for quite some time, but really only wanted to upload now, using something else to actually take the screenshot. With that tool, when I am authed and upload an image with no album, it would show up under my accounts images, which default to private unless I share the link. I was under the impression that this tool would function in a similar manner, but after authing and what not, I try to upload an image with no album, I get a link to the image, but it doesn't show up under my account, so I have no idea where it is going. Is it just uploading publically? I definitely am not wanting that, otherwise I would just use flameshots builtin upload. Is there a way with this to ensure that images only upload to my actual account, and if for some reason auth fails, simply don't upload? If it isn't able to and just uploads publically, I am not sure what the auth is being used for?

Thanks,
-MH

**Comment by faustocarrera** [comment]
Hi, thanks for reaching.
No, the image is not public until you share it with the community using the share endpoint.
I'm gonna check the issue and keep you up to date.

**Comment by faustocarrera** [comment]
The image is not public available on the site, but it's available to anyone with the link, and it's not on the posts section because it's not added automatically to an album, it should be on the images section https://{your_user_name}.imgur.com/all/ that it's private.
Hope this clarify the issue.

**Comment by faustocarrera** [comment]
Are you using the authenticated endpoint?
