### ISSUE TITLE
Possible to upload images without a callback access token?

### ISSUE THREAD

**Issue by db0** [faustocarrera/imgur-python#18]
According to the imgur documentation a simple header should be possible. 

```
This also works if you'd like to upload images anonymously (without the image being tied to an account), or if you'd like to create an anonymous album. This lets us know which application is accessing the API.

Authorization: Client-ID YOUR_CLIENT_ID 
```

But this module always assumes an access token will be available

**Comment by db0** [comment]
Yes, I just tested this is happily possible. I'll see if I can send you a PR

**Comment by faustocarrera** [comment]
I'm AFK today, let me check the PR tonight and see if I can merge/version/deploy
