### ISSUE TITLE
How to submit publicly?

### ISSUE THREAD

**Issue by Mr-Steal-Your-Script** [faustocarrera/imgur-python#9]

**Comment by Mr-Steal-Your-Script** [comment]
`KeyError: 'access_token'`

no matter what I do

**Comment by faustocarrera** [comment]
Did you followed the [necessary steps](https://github.com/faustocarrera/imgur-python/wiki/Authorize) to authorize your account? And if you have a token, are you sending it when you instantiate the class as a [config dictionary](https://github.com/faustocarrera/imgur-python/wiki/Config)?

**Comment by Mr-Steal-Your-Script** [comment]
> And if you have a token, are you sending it when you instantiate the class as a [config dictionary](https://github.com/faustocarrera/imgur-python/wiki/Config)?

Thanks, was missing that :)
